[DebugInfo] Support dereferencing of scalar pointer variable inside gdb
flang-compiler/flang pull request #1140
Opened 2021-09-21 10:13 UTC by alokkrsharma

Please consider below testcase
````
program main
integer, pointer :: sclrptr
allocate(sclrptr)
sclrptr = 9
print *, sclrptr
end
`````
After the fix.
Flang produced binary behaves same as gfortran as below.
```````````
(gdb) p sclrptr
$3 = (PTR TO -> ( integer )) 0x605280
(gdb) p *sclrptr
$4 = 9
```````````

2021-09-22 07:07 UTC, alokkrsharma commented
Hi @kiranchandramohan, @bryanpkc , @shivaramaarao , @pawosm-arm , Can you please spend some time to review this ?

2021-09-22 07:44 UTC, pawosm-arm commented
Is the commit in this PR included in the other PR too?

2021-09-22 07:49 UTC, pawosm-arm requested changes
the commit message is slightly unclear. Is the quoted flang behavior before or after applying this patch?
Note that your PR comment seems more informative. But in the future, people will be looking at git log more often than at the comments of closed PR's.

2021-09-22 08:37 UTC, alokkrsharma commented
> 
> 
> Is the commit in this PR included in the other PR too?

Yes, the first one.
The second one (procedure pointer) is based on first commit (scalar pointer).

2021-09-23 04:24 UTC, closed without merging

2021-09-23 04:25 UTC, alokkrsharma commented
#1141 is superset of this. So closing this.