Fix implicit declaration of function warnings reported by clang-cl
flang-compiler/flang pull request #1158
Opened 2021-10-21 16:18 UTC by kaadam

It needs to include the proper header files to silence warnings for
access, chdir, chmod, ulink, write functions.

2021-11-01 09:27 UTC, pawosm-arm approved these changes

2021-11-03 18:15 UTC, isuruf approved these changes

2021-11-25 09:20 UTC, kaadam commented
@bryanpkc @kiranchandramohan Could you take a look at this PR? Thanks.

2022-03-09 14:01 UTC, bryanpkc requested changes
This PR replaces uses of the `WIN32` and `WIN64` macros with `_WIN64`, however these macros are still used in many files under the `runtime/` folder. `_WIN32` continues to be used in `tools/shared/utils/gbldefs.h` and some `f90_correct` tests. Could you leave the macros unchanged in this PR, but create another PR to change all the macros uniformly?

2022-03-09 14:03 UTC, bryanpkc commented
Oh wait, that PR is already created (#1163). I suggest we review and merge that one, before rebasing this one.

2022-12-17 00:31 UTC, bryanpkc commented
This needs a rebase.

2023-01-25 11:21 UTC, bryanpkc approved these changes

2023-01-30 13:31 UTC, kaadam commented
@bryanpkc Shall I merge this PR, or may I ask you to do that?

2023-01-30 14:25 UTC, merged