Implementing vscale_range into Flang
flang-compiler/flang pull request #1187
Opened 2021-12-08 04:23 UTC by abrahamtovarmob

depends on https://github.com/flang-compiler/flang/pull/1173
depends on https://github.com/flang-compiler/flang/pull/1186

Implement msve-vector-bits in classic Flang. Implementing vscale_range with the functionallity to read from msve-vector-bits to be able to manipulate the range of the scale. for vscale_range(X/128, X/128)

Important to add the previous commits since the base of this work need those changes too.

2022-01-11 15:31 UTC, pawosm-arm requested changes

2022-01-11 15:31 UTC, pawosm-arm commented on test/llvm_ir_correct/attr.f90
> +! ATTRS2: attributes{{.*}}"target-features"="+neon,+sve"
Newline missing after the last line.

2022-01-11 17:59 UTC, pawosm-arm commented on tools/flang2/flang2exe/cgmain.cpp
> +    if(ret) {
`if (ret) {` it should be

2022-01-11 18:00 UTC, pawosm-arm commented on tools/flang2/flang2exe/cgmain.cpp
> +      if(ret) {
same as above

2022-01-12 11:37 UTC, pawosm-arm commented on test/llvm_ir_correct/vscale-mbits.f90
> +! ATTRS3-DAG:"target-features"="+neon,+sve2"
`-march=armv8-a+sve2` implies "+neon,+sve2,+sve", this check will not pass.

The same goes to lines below.

2022-01-12 11:41 UTC, pawosm-arm requested changes
It won't work.

2022-01-12 11:41 UTC, pawosm-arm commented on tools/flang2/flang2exe/cgmain.cpp
> +bool
There's something wrong with this function, it spilled mod equals to `+sve2,+sve` which resulted in `is_vscale_feat()` couldn't recognize `+sve2` in simple `strcmp()`.

2022-01-12 11:55 UTC, pawosm-arm commented on tools/flang2/flang2exe/cgmain.cpp
> +  mod = (char*) calloc(j+1,sizeof(char));
who frees that?!

2022-01-12 13:25 UTC, pawosm-arm commented on tools/flang2/flang2exe/cgmain.cpp
> +  int len = sizeof(*CPU_VSCALE)-1;
that's not how sizeof should be used! `CPU_VSCALE` is an array of pointers, so a single element of it (`*CPU_VSCALE`) is a pointer, on 64-bit machine it is 8 bytes in size, so sizeof returns always 8 here. You were lucky that `CPU_VSCALE` contains 7 elements and that `8 - 1` is also 7.

2022-01-12 14:10 UTC, pawosm-arm commented on tools/flang2/flang2exe/cgmain.cpp
> +is_vscale_feat(char *mod)
should take `const char *mod` instead. The `mod` variable is not modified by this function.

2022-01-15 09:46 UTC, pawosm-arm commented
I need to make a final blow to this PR: flang2 should remain architecture independent, hence vscale_range computation depending on particular VLA implementations should not be computed here. It should be computed in LLVM's frontent driver and passed to flang2 as yet another command line option. Emission of vscale_range should therefore depend on presence of that option.

2022-01-18 05:26 UTC, jdomke reviewed
Sorry to jump in, but I tested this PR and found multiple issues in tools/flang2/flang2exe/cgmain.cpp:

- str1[30] in extract_arch_feat is too small for a64fx which yields '+v8.2a,+fp-armv8,+neon,+crc,+crypto,+fullfp16,+ras,+lse,+rdm,+sve,+sha2,+aes' in arch_feat string
- extract_arch_feat extracts everything after the 1st comma
- is_vscale_feat assumes single feature token, but gets multiple comma-separed tokens, hence strcmp fails to find anything unless you are lucky and +sve is in 2nd position of original string
- provided test cases are insufficiant since they all yield a similar '+neon,+sve..' arch_feat string and hence don't find any of the errors which I ran into with realistic march/mcpu flags

2022-01-18 12:12 UTC, pawosm-arm commented
A decision was made that this feature needs to be provided by a new PR introducing different implementation shifting more of the logic to the frontend driver.

2022-01-18 12:12 UTC, closed without merging