[runtime] Fix bug in iso_fortran_env.f90 (encountered in OpenMPI)
flang-compiler/flang pull request #1222
Opened 2022-02-09 02:59 UTC by zhaochuanfeng

After #1129 commited, a regression is generated when compiling OpenMPI. 
_Originally posted by @pawosm-arm in https://github.com/flang-compiler/flang/issues/1129#issuecomment-1030595159_

This PR fix this issue by correctly declaring REAL128 kind parameter.

2022-02-09 09:17 UTC, pawosm-arm approved these changes

2022-02-09 10:52 UTC, pawosm-arm requested changes
This indeed fixes the problem for OpenMPI. Still I'm seeing the same error message in nag test suite, e.g. pd5e.f90 test:
```
$HOME/upstream/llvm-debug/bin/flang -c pd5e.f90
F90-S-0081-Illegal selector - KIND value must be non-negative  (pd5e.f90: 4)
  0 inform,   0 warnings,   1 severes, 0 fatal for pd5e
F90-S-0081-Illegal selector - KIND value must be non-negative  (pd5e.f90: 7)
F90-S-0081-Illegal selector - KIND value must be non-negative  (pd5e.f90: 22)
F90-S-0081-Illegal selector - KIND value must be non-negative  (pd5e.f90: 23)
F90-S-0081-Illegal selector - KIND value must be non-negative  (pd5e.f90: 24)
  0 inform,   0 warnings,   3 severes, 0 fatal for test
```
First seven lines are:

2022-02-10 21:47 UTC, pawosm-arm commented
I think this PR is premature. It would be better to wait for the completion of Quad-FP works.

I've tried the new changes in our CI, but sadly, although pd5e test case compiles with the new patch, it segfaults when executed:
```
Test pd5e FAILED: on execution:
*** res/pd5e.res        Thu Feb 10 15:27:47 2022
--- pd5e.out    Thu Feb 10 15:28:02 2022
***************
*** 1,4 ****
!  F
!  T
!       1.2345678901234567890123
!  ok
--- 1 ----
! Segmentation fault (core dumped)
```

2022-02-24 06:40 UTC, bryanpkc commented
@pawosm-arm I can reproduce the segfault even after I reverted commit 46ec115bed6c. In fact, the integer test case pd5.f90 also crashes for me. The problem is that Flang doesn't seem to handle `value, optional` dummy arguments correctly, and generates LLVM IR for the actual argument that loads from a null pointer. Does pd5.f90 run fine in your tests?

[Our wiki page on Fortran 2008 features](https://github.com/flang-compiler/flang/wiki/Fortran-2008) seems to list this as a known unsupported feature.

2022-02-24 10:25 UTC, pawosm-arm commented
@bryanpkc this only confirms my suspicion that with QuadFP enabled, more tests are executed. I've looked into our CI logs and see that after reverting QuadFP commits, the only `pd`-prefixed tests that were executed are `pd0.f`, `pd0a.f`, `pd0b.f` and `pd0c.f`. So I assume, `pd5` and `pd5e` cases need to be added to disabled list. Sadly, this still does not end the problem, as even with this PR applied, there are more of the test cases failing at compile time with `KIND value must be non-negative`.

2022-02-24 10:27 UTC, pawosm-arm approved these changes
This patch fixes the initial issue with OpenMPI, so it can be merged. All other issues need to be addressed with further actions.

2022-03-09 16:16 UTC, bryanpkc commented
Thanks for the approvals.

2022-03-09 16:17 UTC, merged