Fix for regression introduced by PR #1101.
flang-compiler/flang pull request #1279
Opened 2022-07-22 08:04 UTC by qiaozhang-hnc

The root cause is that when an empty derived type parameter is declared in module,
an ACL structure for that parameter is generated, but its subc node is empty and
exported to the MOD file. But when importing the MOD file, flang cannot get the
information of this empty subc node.

This commit adds a flag to the MOD file to indicate whether the ACL structure
for the derived type parameter has a subc node.

2022-07-22 09:09 UTC, pawosm-arm approved these changes
Thanks for prompt reaction!

2022-07-22 13:41 UTC, bryanpkc approved these changes

2022-07-22 14:40 UTC, kiranchandramohan commented
Is this changing the module format? If so, we should change the version number.
Also there should be a test to check the module generated.

2022-07-22 15:17 UTC, pawosm-arm requested changes
please update `IVSN` and add a note in the `interf.h` comment.

2022-07-23 08:59 UTC, pawosm-arm approved these changes

2022-07-23 14:28 UTC, pawosm-arm commented
@kiranchandramohan are you happy with current shape?

2022-07-25 14:50 UTC, merged