Trailz function added to the fortran compiler
flang-compiler/flang pull request #737
Opened 2019-06-21 09:23 UTC by CarolineConcatto

Signed-off-by: Caroline Concatto <caroline.concatto@arm.com>

2020-09-01 13:06 UTC, kiranchandramohan commented
@CarolineConcatto can you rebase?

2020-09-02 07:41 UTC, shivaramaarao commented on runtime/flang/ktrailz.c
> +   return ((int)(ui))?( __builtin_ctz(ui)): (__builtin_ctz(ui>>32+32));
+32 need to be outside the bracket here
(__builtin_ctz(ui>>32))+32

2020-09-03 14:31 UTC, shivaramaarao approved these changes

2020-09-03 15:41 UTC, gklimowicz requested changes

2020-09-03 15:41 UTC, gklimowicz commented on tools/flang2/utils/ilmtp/ppc64le/ilmtp.n
> +.IL TRAILZ intr lnk
Still doesn't build on Power without this change...

2020-09-03 16:02 UTC, kiranchandramohan commented on tools/flang2/utils/ilmtp/ppc64le/ilmtp.n
> +.IL TRAILZ intr lnk
You mean it still **doesn't** build with this change?

2020-09-03 16:31 UTC, gklimowicz commented on tools/flang2/utils/ilmtp/ppc64le/ilmtp.n
> +.IL TRAILZ intr lnk
No, still doesn't compile.

I think it needs to be **B**TRAILZ, like it is in `tools/flang2/utils/ilmtp/aarch64/ilmtp.n` and `tools/flang2/utils/ilmtp/x86_64/ilmtp.n`

2020-09-04 06:47 UTC, CarolineConcatto commented on tools/flang2/utils/ilmtp/ppc64le/ilmtp.n
> +.IL TRAILZ intr lnk
Thank you @gklimowicz. 
Can you build again with the change to see if it works?

2020-09-04 16:34 UTC, gklimowicz approved these changes
Builds on OpenPOWER now. Thanks, Carol.

2020-09-04 17:14 UTC, merged