Implement UNROLL directive
flang-compiler/flang pull request #742
Opened 2019-06-25 10:30 UTC by CarolineConcatto

Signed-off-by: Caroline Concatto <caroline.concatto@arm.com>
This patch implements UNROLL pragma.
However in order for it to work it depends on a previous patch #660

2020-10-22 01:48 UTC, gklimowicz requested changes
Since this PR says it is dependent on PR#660, I applied the patches (660.patch and 742.patch) and got conflicts. details below.
```
error: patch failed: tools/flang2/flang2exe/cgmain.cpp:1565
error: tools/flang2/flang2exe/cgmain.cpp: patch does not apply
error: patch failed: tools/flang2/flang2exe/iltutil.cpp:331
error: tools/flang2/flang2exe/iltutil.cpp: patch does not apply
error: patch failed: tools/flang2/flang2exe/mwd.cpp:4893
error: tools/flang2/flang2exe/mwd.cpp: patch does not apply
Makefile.pr1:17: recipe for target 'src.pr742.90/made' failed
```

It looks like this pull request contains some changes that were already made in #685 

And the PR does not build at all without the changes from #660 (that is, I can't just apply #742 alone).

2020-10-22 01:48 UTC, gklimowicz commented on tools/flang2/flang2exe/iltutil.cpp
> +    fprintf(ff, " NOSIMD");
The patch fails here. These two lines (334-335) were already included in PR #660.

2020-10-22 01:48 UTC, gklimowicz commented on tools/flang2/flang2exe/cgmain.cpp
>        }
The patch file here fails to apply. These three lines (1565-1567) were removed in PR #660 and replaced with other text.
```
@@ -1557,15 +1556,20 @@ schedule(void)
       merge_next_block = false;
     }

-    if (XBIT(183, 0x10000000)) {
-      if ((!XBIT(69, 0x100000)) && BIH_NODEPCHK(bih) &&
-          (!ignore_simd_block(bih))) {
-        fix_nodepchk_flag(bih);
-        mark_rw_nodepchk(bih);
-      } else {
-        clear_rw_nodepchk();
-      }
+    open_pragma(BIH_LINENO(bih));
+    BIH_NODEPCHK(bih) = !flg.depchk;
+    if(XBIT(19, 0x18))
+      BIH_NOSIMD(bih) = true;
+    else if(XBIT(19, 0x400))
+      BIH_SIMD(bih) = true;
+    if ((!XBIT(69, 0x100000)) && BIH_NODEPCHK(bih) &&
+        (!ignore_simd_block(bih))) {
+      fix_nodepchk_flag(bih);
+      mark_rw_nodepchk(bih);
+    } else {
+      clear_rw_nodepchk();
     }
+    close_pragma();

     for (ilt = BIH_ILTFIRST(bih); ilt; ilt = ILT_NEXT(ilt)) {
       if (BIH_EN(bih) && ilt == BIH_ILTFIRST(bih)) {
```

2020-10-22 01:48 UTC, gklimowicz commented on tools/flang2/flang2exe/mwd.cpp
> +  putbit("nosimd", BIH_NOSIMD(block));
The patch fails here. PR #660 already includes this line 4898.

2020-10-22 19:43 UTC, kiranchandramohan commented
Thanks @gklimowicz for the review. Since some of the changes in this patch are inside the changes in https://github.com/flang-compiler/flang/pull/660, it is not easy to make this apply cleanly. I guess it is best to wait till the other patch is in.

2020-10-25 21:36 UTC, bryanpkc commented
I have submitted #942. That PR consists of both #660 and a revised version of this one (to resolve merge conflicts and delete some unnecessary delta), and also extends the `UNROLL` directive to support user-specified unroll factors.

2020-10-29 08:36 UTC, kiranchandramohan commented
Closing this patch in favour of https://github.com/flang-compiler/flang/pull/942 by @bryanpkc. https://github.com/flang-compiler/flang/pull/942 contains changes in this patch and will attribute @CarolineConcatto the author. Reopen in case of disagreement.

2020-10-29 08:36 UTC, closed without merging